clc
clear
clf
img=imread('pic.png');
length(img)
subplot(221)
imshow(img)
title('原照片')
[U,S,V]=svds(double(img(:,:,1)),21);
imgc1(:,:,1)=U*S*V';
[U,S,V]=svds(double(img(:,:,2)),21);
imgc1(:,:,2)=U*S*V';
[U,S,V]=svds(double(img(:,:,3)),21);
imgc1(:,:,3)=U*S*V';
subplot(222)
imshow(uint8(imgc1))
title('前5%的奇异值')
[U,S,V]=svds(double(img(:,:,1)),42);
imgc1(:,:,1)=U*S*V';
[U,S,V]=svds(double(img(:,:,2)),42);
imgc1(:,:,2)=U*S*V';
[U,S,V]=svds(double(img(:,:,3)),42);
imgc1(:,:,3)=U*S*V';
subplot(223)
imshow(uint8(imgc1))
title('前10%的奇异值')
[U,S,V]=svds(double(img(:,:,1)),84);
imgc1(:,:,1)=U*S*V';
[U,S,V]=svds(double(img(:,:,2)),84);
imgc1(:,:,2)=U*S*V';
[U,S,V]=svds(double(img(:,:,3)),84);
imgc1(:,:,3)=U*S*V';
subplot(224)
imshow(uint8(imgc1))
title('前20%的奇异值')