clear
clc
%设置x与y
x1=linspace(-pi,pi,100);
x2=linspace(pi,4*pi,100);
x3=linspace(1,8,100);
y1=x1.*cos(x1);
y2=x2.*tan(1./x2).*sin(x2.^3);
y3=exp(1./x3).*sin(x3);
%第一个图
subplot(1,3,1)
plot(x1,y1,"b.-");
axis([-pi,pi,-4,4])
title("y=xcosx在-pi到pi间的图像")
xlabel("x")
ylabel("y")
legend("y=xcosx");
%第二个图
subplot(1,3,2)
plot(x2,y2,"r.-");
title("y=xtan(1/x)sin(x^3)在pi到4pi间的图像")
xlabel("x")
ylabel("y")
axis([pi,4*pi,-4,4])
legend("y=xtan(1/x)sin(x^3)");
%第三个图
subplot(1,3,3)
plot(x3,y3,"g.-");
title("y=e^{1/x}sinx在1到8间的图像")
xlabel("x")
ylabel("y")
axis([1,8,-4,4])
legend("y=e^{1/x}sinx");
%gtext
gtext("y=xcosx");
gtext("y=xtan(1/x)sin(x^3)");
gtext("y=e^{1/x}sinx");
